# This is a basic workflow to help you get started with Actions

name: Push to staging

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: .
          destination-github-username: 'test-action-pages'
          destination-repository-name: 'staging'
          user-email: cicd@nehfamim.com
          commit-message: $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
